receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "gomall"
    const_labels:
      app: "gomall"
      environment: "production"
  
  logging:
    loglevel: debug
  
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true
  
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [jaeger, zipkin, logging]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus, logging]
  
  telemetry:
    logs:
      level: "debug"
