// Code generated by hertz generator.

package example

import (
	"context"
	"fmt"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	example "zqzqsb.com/gomall/demo/hex/kitex_gen/hello/example"
)

// HelloMethod .
// @router /hello [GET]
func HelloMethod(ctx context.Context, c *app.RequestContext) {
	var err error
	var req example.HelloReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(example.HelloResp)
	resp.RespBody = fmt.Sprintf("[HERTZ] hello, %s", req.Name)
	c.JSON(consts.StatusOK, resp)
}
