env: dev

kitex:
  service: gomall.user
  address: :8888
  log_level: info
  log_file_name: log/kitex.log
  log_max_size: 10
  log_max_backups: 50
  log_max_age: 30
  metrics_port: :9991

mysql:
  dsn: root:123456@tcp(localhost:3306)/gomall_user?charset=utf8mb4&parseTime=True&loc=Local

redis:
  address: localhost:6379
  username: 
  password: 
  db: 0

# Redis Cluster 配置
redis_cluster:
  enabled: true
  addrs:
    - localhost:6379
    - localhost:6380
    - localhost:6381
    - localhost:6382
    - localhost:6383
    - localhost:6384
  username: 
  password: 
  max_retries: 3
  min_retry_backoff: 8ms
  max_retry_backoff: 512ms
  route_by_latency: true
  route_randomly: true

registry:
  registry_address:
    - 127.0.0.1:8500
