// Code generated by hertz generator.

package user

import (
	"context"
	"fmt"
	"log"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/hertz-contrib/csrf"
	"zqzqsb.com/gomall/app/user/biz/service"
	user "zqzqsb.com/gomall/app/user/kitex_gen/user"
)

// Register .
// @router /register [POST]
func Register(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.RegisterReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 调用 RPC 服务进行注册
	registerService := service.NewRegisterService(ctx)
	resp, err := registerService.Run(&req)
	if err != nil {
		c.String(consts.StatusInternalServerError, fmt.Sprintf("Registration failed: %v", err))
		return
	}

	// 返回注册响应
	c.JSON(consts.StatusOK, resp)

}

// Login .
// @router /login [POST]
func Login(ctx context.Context, c *app.RequestContext) {
	var err error
	var req user.LoginReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	userID := c.GetString("identity")
	log.Println("user:", userID)

	LoginService := service.NewLoginService(ctx)
	resp, err := LoginService.Run(&req)
	if err != nil {
		c.String(consts.StatusInternalServerError, fmt.Sprintf("Registration failed: %v", err))
		return
	}

	c.JSON(consts.StatusOK, resp)
}

// Hello .
// @router /hello [GET]
func Hello(ctx context.Context, c *app.RequestContext) {
	// 1. Bind & Validate 请求参数
	var req user.HelloReq
	if err := c.BindAndValidate(&req); err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	// 2. 打印当前请求中所有的 Cookie
	cookies := c.Request.Header.FullCookie() // 获取所有 Cookies
	log.Println("cookies:", string(cookies))

	// 如果只想获取特定 Cookie（比如 "jwt"），可以：
	jwtCookie := c.Request.Header.Cookie("jwt")
	log.Println("jwt Cookie Value:", string(jwtCookie))

	// 3. 打印当前用户ID（从 JWT 中获取）
	userID := c.GetInt64("identity")
	log.Println("user:", userID)

	// 4. 获取 CSRF Token
	csrfToken := csrf.GetToken(c)

	// 5. 返回响应
	resp := &user.HelloResp{
		RespBody: csrfToken,
	}
	c.JSON(consts.StatusOK, resp)
}
