global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
        labels:
          instance: redis-cluster

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9091']
        labels:
          instance: prometheus
