version: "3"
services:
  mysql:
    image: "mysql:latest"
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=gorm
      - MYSQL_USER=gorm
      - MYSQL_PASSWORD=gorm
      - MYSQL_RANDOM_ROOT_PASSWORD="yes"
  redis:
    image: "redis:latest"
    ports:
      - 6378:6379
  consul:
    image: "consul:1.15.0"
    container_name: consul-server
    ports:
      - "8500:8500" # Consul Web UI 和 HTTP API 的端口
      - "8600:8600/udp" # DNS 服务的 UDP 端口
    environment:
      CONSUL_BIND_INTERFACE: eth0
    command: agent -server -bootstrap -ui -client=0.0.0.0
